name: Profile Readme

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TITLE: true
          TIME_RANGE: "all_time"
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
          LANG_COUNT: 7
#           SHOW_SHORT_INFO: "False"
#           SHOW_PROFILE_VIEWS: "False"
#           SHOW_LINES_OF_CODE: "True"
#           SHOW_LANGUAGE_PER_REPO: "False"
#           SHOW_COMMIT: "False"
#           SHOW_DAYS_OF_WEEK: "False"
#           SHOW_PROJECTS: "False"
#           SYMBOL_VERSION: 3
          
#   devcard:
#     name: Update Dev Card
#     runs-on: ubuntu-latest
#     steps:
#       - name: devcard
#         uses: dailydotdev/action-devcard@2.0.2
#         with:
#           devcard_id: ${{ secrets.DEVCARD_ID }}
